# This is a basic workflow to help you get started with Actions

name: test action 2

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  schedule:
#   - cron:  '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Install playwright
        run: npm install playwright
        
      - name: Install ocrspace
        run: npm i ocr-space-api-wrapper
        
      - name: run playwright
        run: node test.js $NAME $PW $OCRKEY
        env:
          NAME: ${{ secrets.NAME }}
          PW: ${{ secrets.PW }}
          OCRKEY: ${{ secrets.OCRKEY }}
      
